name: Deploy React Application to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate version number
        id: version  # Step ID for referencing the version output
        run: echo "VERSION=$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV  # Generate version number and save to env file

      - name: Create .env file
        run: echo "REACT_APP_VERSION=${{ env.VERSION }}" > .env  # Write version number to .env file          

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        env:
          CI: false
          REACT_APP_LIFF_ID: ${{ secrets.REACT_APP_LIFF_ID }}
          REACT_APP_USERNAME: ${{ secrets.REACT_APP_USERNAME }}
          REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}
          REACT_APP_VERSION: ${{ env.VERSION }}  # Pass version to build environment
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Output GitHub Pages URL
        run: echo "Deployed successfully! View your site at: http://nopparat-mkw.github.io/line-liff-app/"          
